name: Publish Python Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          echo "Setting Poetry to use correct Python version"
          poetry env use python3
        shell: pwsh

      - name: Debug Poetry Environment
        run: |
          poetry env info
        shell: pwsh

      - name: Remove Existing Poetry Virtual Environment (if any)
        run: |
          poetry env remove python || echo "No existing env found"
        shell: pwsh
        continue-on-error: true

      - name: Install dependencies
        run: poetry install --no-interaction --no-root
        shell: pwsh

      - name: Run Tests
        run: poetry run pytest
        env:
          PYTHONPATH: ${{ github.workspace }}
        shell: pwsh

      - name: Build package
        run: poetry build
        shell: pwsh

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry publish --no-interaction
        shell: pwsh
