name: Publish Python Package

on:
  push:
    branches:
      - main  # Runs on push to 'main' branch

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "poetry"  # Cache dependencies for faster builds

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          echo "C:\Users\runneradmin\AppData\Roaming\Python\Scripts" >> $GITHUB_PATH
          echo "C:\Users\runneradmin\AppData\Roaming\Python\Scripts" >> $PATH
          poetry --version  # Check if Poetry is installed correctly

      - name: Install dependencies
        run: poetry install --no-interaction --no-root  # Ensure dependencies are installed

      - name: Run Tests
        run: poetry run pytest
        env:
          PYTHONPATH: ${{ github.workspace }}  # Ensure package is discoverable

      - name: Build package
        run: poetry build

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}  # Use secure API token
        run: poetry publish --no-interaction
