name: Publish Python Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use Windows since Poetry has issues with explicit versions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Verify Python & Poetry
        run: |
          python --version
          poetry --version

      - name: Set Poetry to Use System Python (Fixes python3.9 error)
        run: poetry env use python  # Use 'python' instead of 'python3.9'

      - name: Show Poetry Environment Info
        run: poetry env info

      - name: Install Dependencies
        run: poetry install --no-interaction --no-root

      - name: Run Tests
        run: poetry run pytest
        env:
          PYTHONPATH: ${{ github.workspace }}

      - name: Build Package
        run: poetry build

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry publish --no-interaction
