name: Publish Python Package

on:
  push:
    branches:
      - main  # Runs on push to 'main' branch

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry self update
        shell: pwsh

      - name: Verify Poetry Installation
        run: poetry --version
        shell: pwsh

      - name: Install dependencies
        run: poetry install --no-interaction --no-root
        shell: pwsh

      - name: Run Tests
        run: poetry run pytest
        env:
          PYTHONPATH: ${{ github.workspace }}
        shell: pwsh

      - name: Build package
        run: poetry build
        shell: pwsh

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry publish --no-interaction
        shell: pwsh
